[build]
  publish = "frontend/dist"
  command = "cd frontend && npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://backendv1-uhsl.onrender.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://backendv1-uhsl.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
