services:
  # Backend Service
  - type: web
    name: lucksnap-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:soOPSwrlxnEjSmXKXzsFZJNrgfLQqzyC@centerbeam.proxy.rlwy.net:27393/railway
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Service
  - type: static
    name: lucksnap-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://lucky-snap-djy0.onrender.com/api
