services:
  # Backend Service
  - type: web
    name: lucky-snap-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.19.0
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false

  # Frontend Service
  - type: static
    name: lucky-snap-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build:frontend
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://lucky-snap-backend.onrender.com/api
